channels:
  - conda-forge
dependencies:
  - python=3
  - dask
  - dask-ml
  - dask-labextension>=1.0
  - bokeh
  - ipywidgets
  - jupyterlab>=1.0
  - nbserverproxy
  - nodejs
  - pytables
  - python-graphviz
